version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: challenges-postgres
    environment:
      POSTGRES_DB: challenges
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: challenges2024
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
